baseURL = 'https://example.org/'
language = 'en-us'
title = 'The Repository of an Open Mind'
theme = 'Papermod'
[params]
    description = 'A personal blog about technology, philosophy, and life.'
    author = 'Rounak Paul'
    
    
    
